version: "3"

networks:
  docker-project-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  backend:
    container_name: "backend"
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      docker-project-network:
        ipv4_address: 172.20.0.12

  frontend:
    container_name: "frontend"
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      docker-project-network:
        ipv4_address: 172.20.0.14
    depends_on:
      - backend

volumes:
  db-data:
