version: "3"

networks:
  docker-project-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      docker-project-network:
        ipv4_address: 172.20.0.10

  backend:
    container_name: "backend"
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: bash -c "dotnet ef database update"
    networks:
      docker-project-network:
        ipv4_address: 172.20.0.12
    depends_on:
      - db

  frontend:
    container_name: "frontend"
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      docker-project-network:
        ipv4_address: 172.20.0.14
    depends_on:
      - backend

volumes:
  db-data:
